#! /bin/sh
### BEGIN INIT INFO
# Provides:          music
# Required-Start:    alsa-utils
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Background music service
# Description:       Play default configured music in background
#
### END INIT INFO
### Copyright(c) 2014 OpenDomo Services SL. Licensed under GPL v3 or later

. /lib/init/vars.sh
. /lib/lsb/init-functions

MUSICPID="/var/opendomo/run/musicplayer.pid"
CONFIGFILE="/etc/opendomo/music.conf"
MPDPIDFILE="/var/opendomo/run/mpd.pid"
ODPCOMMAND="/usr/local/opendomo/bin/musicPlayer.sh"

do_start () {
    if test -f $MPDPIDFILE && [ `head -n1 "$CONFIGFILE" | cut -f1 -d=` != "no_configured" ]; then
        # Extract configuration
        ARTIST=`grep ALBUM $CONFIGFILE | cut -f2 -d=`"
        RDM=`grep RDM $CONFIGFILE | cut -f2 -d=`"
        LOOP=`grep LOOP $CONFIGFILE | cut -f2 -d=`"
        VOLUME=`grep VOLUME $CONFIGFILE | cut -f2 -d=`"

        # Configure player & start
	$ODPCOMMAND random $RDM    &>/dev/null
	$ODPCOMMAND loop $LOOP     &>/dev/null
	$ODPCOMMAND volume $VOLUME &>/dev/null
	$ODPCOMMAND play "$ARTIST" &>/dev/null
    fi
}

do_stop () {
    if test -f $MUSICPID; then
        $ODPCOMMAND stop &>/dev/null
    fi
}

do_status () {
    if ! test -f $MUSICPID; then
        echo "music not running"
        exit 1
    else
        echo "music is running"
        exit 0
    fi
}

case "$1" in
    start|"")
        log_daemon_msg "Starting opendomo music player"
        do_start
        log_end_msg $?
        ;;
    restart|reload|force-reload)
        do_start
        do_stop
        exit 3
        ;;
    stop)
        log_daemon_msg "Stoping opendomo music player"
        do_stop
        log_end_msg $?
        exit 3
        ;;
    status)
        do_status
        exit $?
        ;;
    *)
        echo "Usage: music [start|stop|restart|status]" >&2
        exit 3
        ;;
esac

:
